/* global window */
window.__PULSO__ = {

  brand: {
    name: "Pulso",
    tagline: "La IA, sin filtros.",
    taglineEn: "AI, without the noise.",
    domain: "pulso.ai",
    social: {
      twitter: "https://twitter.com/pulsoai",
      linkedin: "https://linkedin.com/company/pulsoai",
      rss: "/rss.xml"
    }
  },

  ticker: [
    "GPT-4o actualiza visión multimodal · junio 2026",
    "DeepSeek R2 rompe récord en MATH · mayo 2026",
    "Gemini 2.5 Ultra llega a consumidores",
    "Apple Intelligence integra Claude 3.7",
    "Llama 4 Maverick supera 400B parámetros",
    "OpenAI lanza GPT-4.5 para empresas",
    "Midjourney v7 genera vídeo de 30 segundos",
    "Anthropic anuncia Claude 4 para Q3 2026",
    "EU AI Act entra en vigor para modelos frontier",
    "Runway Gen-4 alcanza 4K a 60fps"
  ],

  models: [
    {
      id: "gpt4o",
      name: "GPT-4o",
      company: "OpenAI",
      category: "Multimodal",
      quote: "El estándar que todos quieren superar.",
      accentColor: "#6C63FF",
      scores: { mmlu: 88.7, humaneval: 90.2, math: 76.6 },
      context: "128K",
      speed: "Rápido",
      pricing: { input: "$2.50", output: "$10.00", unit: "por M tokens" },
      pulsoscore: 9.2,
      open: false,
      url: "https://openai.com",
      icon: "M40 20a20 20 0 1 0 0 40 20 20 0 0 0 0-40zm0 6l12 20H28zm0 8l8 14H32z"
    },
    {
      id: "claude37",
      name: "Claude 3.7 Sonnet",
      company: "Anthropic",
      category: "Razonamiento",
      quote: "La honestidad como ventaja competitiva.",
      accentColor: "#D4A754",
      scores: { mmlu: 88.3, humaneval: 93.7, math: 78.2 },
      context: "200K",
      speed: "Moderado",
      pricing: { input: "$3.00", output: "$15.00", unit: "por M tokens" },
      pulsoscore: 9.4,
      open: false,
      url: "https://anthropic.com",
      icon: "M40 14l18 32H22zm0 10l10 18H30zm-4 22h8v4h-8z"
    },
    {
      id: "gemini25pro",
      name: "Gemini 2.5 Pro",
      company: "Google DeepMind",
      category: "Multimodal",
      quote: "Un millón de tokens. Serio.",
      accentColor: "#4285F4",
      scores: { mmlu: 90.0, humaneval: 87.0, math: 91.0 },
      context: "1M",
      speed: "Moderado",
      pricing: { input: "$1.25", output: "$10.00", unit: "por M tokens" },
      pulsoscore: 9.3,
      open: false,
      url: "https://deepmind.google",
      icon: "M40 16a24 24 0 1 0 1 0zm0 8a16 16 0 1 1-1 0zm8 8H40v-8h8v8z"
    },
    {
      id: "deepseekr1",
      name: "DeepSeek R1",
      company: "DeepSeek",
      category: "Razonamiento",
      quote: "Open-source que sacudió Wall Street.",
      accentColor: "#0EA5E9",
      scores: { mmlu: 90.8, humaneval: 86.7, math: 97.3 },
      context: "64K",
      speed: "Lento",
      pricing: { input: "$0.55", output: "$2.19", unit: "por M tokens" },
      pulsoscore: 9.1,
      open: true,
      url: "https://deepseek.com",
      icon: "M22 22c0-10 16-16 18-4s-8 16-8 16 2 8-4 12m8-28c8 4 10 18 2 22"
    },
    {
      id: "grok3",
      name: "Grok 3",
      company: "xAI",
      category: "General",
      quote: "La IA que no se autocensura.",
      accentColor: "#E5E5E5",
      scores: { mmlu: 87.5, humaneval: 88.0, math: 79.0 },
      context: "128K",
      speed: "Rápido",
      pricing: { input: "$3.00", output: "$15.00", unit: "por M tokens" },
      pulsoscore: 8.7,
      open: false,
      url: "https://x.ai",
      icon: "M20 20l20 20m0-20L20 40m10-20v20"
    },
    {
      id: "llama4scout",
      name: "Llama 4 Scout",
      company: "Meta AI",
      category: "Open Source",
      quote: "El gigante de código abierto.",
      accentColor: "#1877F2",
      scores: { mmlu: 79.6, humaneval: 79.6, math: 65.0 },
      context: "10M",
      speed: "Variable",
      pricing: { input: "Gratis", output: "Gratis", unit: "local / $0.11 API" },
      pulsoscore: 8.2,
      open: true,
      url: "https://llama.meta.com",
      icon: "M26 18c-4 8-4 20 0 28m8-28c4 8 4 20 0 28M22 32h16"
    },
    {
      id: "mistral",
      name: "Mistral Large 2",
      company: "Mistral AI",
      category: "Eficiencia",
      quote: "Europa tiene su campeón.",
      accentColor: "#FF7000",
      scores: { mmlu: 84.0, humaneval: 92.0, math: 71.0 },
      context: "128K",
      speed: "Muy rápido",
      pricing: { input: "$2.00", output: "$6.00", unit: "por M tokens" },
      pulsoscore: 8.6,
      open: false,
      url: "https://mistral.ai",
      icon: "M20 24h20M20 32h20M20 40h14m-8-24l10 8-10 8"
    },
    {
      id: "qwen25",
      name: "Qwen 2.5 Max",
      company: "Alibaba",
      category: "Multilingüe",
      quote: "El modelo que domina el chino y el inglés.",
      accentColor: "#FF6A00",
      scores: { mmlu: 85.0, humaneval: 85.0, math: 75.0 },
      context: "128K",
      speed: "Rápido",
      pricing: { input: "$0.40", output: "$1.20", unit: "por M tokens" },
      pulsoscore: 8.4,
      open: true,
      url: "https://qwen.readthedocs.io",
      icon: "M40 18a22 22 0 1 0 .01 0zm0 6v10l8 6"
    },
    {
      id: "phi4",
      name: "Phi-4",
      company: "Microsoft",
      category: "Eficiencia",
      quote: "El modelo pequeño que piensa en grande.",
      accentColor: "#00A4EF",
      scores: { mmlu: 84.8, humaneval: 82.6, math: 80.4 },
      context: "16K",
      speed: "Muy rápido",
      pricing: { input: "$0.07", output: "$0.14", unit: "por M tokens" },
      pulsoscore: 8.0,
      open: true,
      url: "https://microsoft.com/phi",
      icon: "M28 18v28M52 18v28M34 32h-6v-8h6m6 0h6v8h-6"
    },
    {
      id: "gemma3",
      name: "Gemma 3 27B",
      company: "Google",
      category: "Open Source",
      quote: "Potencia de Google, pesos abiertos.",
      accentColor: "#34A853",
      scores: { mmlu: 74.0, humaneval: 72.0, math: 62.0 },
      context: "128K",
      speed: "Variable",
      pricing: { input: "Gratis", output: "Gratis", unit: "local" },
      pulsoscore: 7.8,
      open: true,
      url: "https://ai.google.dev/gemma",
      icon: "M32 18h16l-8 14h8l-16 14 4-12h-8z"
    }
  ],

  tools: [
    { id: "chatgpt",    name: "ChatGPT",         cat: "escritura",    tagline: "El asistente que democratizó la IA",  pulsoscore: 9.2, free: true,  url: "https://chat.openai.com",         emoji: "💬" },
    { id: "jasper",     name: "Jasper",           cat: "escritura",    tagline: "Copywriting de alto rendimiento",    pulsoscore: 8.1, free: false, url: "https://jasper.ai",               emoji: "✍️" },
    { id: "copilot",    name: "GitHub Copilot",   cat: "codigo",       tagline: "Pair programmer en tu IDE",          pulsoscore: 9.0, free: false, url: "https://github.com/features/copilot", emoji: "🤖" },
    { id: "cursor",     name: "Cursor",           cat: "codigo",       tagline: "El IDE que programa contigo",        pulsoscore: 9.3, free: true,  url: "https://cursor.sh",               emoji: "⚡" },
    { id: "midjourney", name: "Midjourney",       cat: "imagen",       tagline: "Arte generativo de nivel profesional", pulsoscore: 9.4, free: false, url: "https://midjourney.com",         emoji: "🎨" },
    { id: "firefly",    name: "Adobe Firefly",    cat: "imagen",       tagline: "Generación segura para marcas",      pulsoscore: 8.5, free: true,  url: "https://firefly.adobe.com",       emoji: "🔥" },
    { id: "runway",     name: "Runway Gen-4",     cat: "video",        tagline: "El estudio de vídeo IA",             pulsoscore: 9.1, free: true,  url: "https://runwayml.com",            emoji: "🎬" },
    { id: "pika",       name: "Pika 2.0",         cat: "video",        tagline: "Vídeo generativo accesible",         pulsoscore: 8.3, free: true,  url: "https://pika.art",                emoji: "🎞️" },
    { id: "elevenlabs", name: "ElevenLabs",       cat: "audio",        tagline: "Voces sintéticas imposibles de distinguir", pulsoscore: 9.2, free: true,  url: "https://elevenlabs.io",  emoji: "🎙️" },
    { id: "whisper",    name: "Whisper",          cat: "audio",        tagline: "Transcripción de OpenAI, código abierto", pulsoscore: 8.8, free: true, url: "https://openai.com/whisper",   emoji: "👂" },
    { id: "notionia",   name: "Notion AI",        cat: "productividad",tagline: "Tu workspace con cerebro",           pulsoscore: 8.6, free: false, url: "https://notion.so",               emoji: "📝" },
    { id: "gamma",      name: "Gamma",            cat: "productividad",tagline: "Presentaciones que se crean solas",  pulsoscore: 8.7, free: true,  url: "https://gamma.app",               emoji: "📊" },
    { id: "perplexity", name: "Perplexity AI",    cat: "investigacion",tagline: "El buscador que cita sus fuentes",   pulsoscore: 9.0, free: true,  url: "https://perplexity.ai",           emoji: "🔍" },
    { id: "elicit",     name: "Elicit",           cat: "investigacion",tagline: "IA para investigación académica",    pulsoscore: 8.4, free: true,  url: "https://elicit.org",              emoji: "📚" },
    { id: "autogpt",    name: "AutoGPT",          cat: "agentes",      tagline: "El agente autónomo pionero",         pulsoscore: 7.9, free: true,  url: "https://agpt.co",                 emoji: "🤖" },
    { id: "make",       name: "Make (Integromat)", cat: "agentes",     tagline: "Automatización sin código con IA",   pulsoscore: 8.8, free: true,  url: "https://make.com",                emoji: "⚙️" }
  ],

  toolCategories: [
    { id: "all",           label: "Todas" },
    { id: "escritura",     label: "Escritura" },
    { id: "codigo",        label: "Código" },
    { id: "imagen",        label: "Imagen" },
    { id: "video",         label: "Vídeo" },
    { id: "audio",         label: "Audio" },
    { id: "productividad", label: "Productividad" },
    { id: "investigacion", label: "Investigación" },
    { id: "agentes",       label: "Agentes" }
  ],

  articles: [
    {
      id: "ganar-dinero-con-ia",
      title: "Cómo ganar dinero con inteligencia artificial en 2026: 12 métodos reales",
      excerpt: "Separamos los métodos que realmente funcionan de los que son humo, con ingresos realistas y primeros pasos concretos para cada uno.",
      tag: "Negocio",
      readTime: 14,
      date: "2026-06-10",
      featured: true,
      accent: "#B89A5C",
      url: "articulos/ganar-dinero-con-ia.html"
    },
    {
      id: "mejores-herramientas-ia-2026",
      title: "Las 10 mejores herramientas de IA en 2026 (gratuitas y de pago)",
      excerpt: "Hemos analizado más de 60 herramientas para seleccionar las 10 que realmente merecen tu tiempo y dinero: código, imagen, vídeo, productividad y más.",
      tag: "Listado",
      readTime: 12,
      date: "2026-06-10",
      featured: true,
      accent: "#6C63FF",
      url: "articulos/mejores-herramientas-ia-2026.html"
    },
    {
      id: "que-es-chatgpt",
      title: "Qué es ChatGPT y para qué sirve en 2026",
      excerpt: "ChatGPT explicado desde cero: cómo funciona, versiones gratuita y Plus, para qué sirve en el trabajo y cuáles son sus limitaciones reales.",
      tag: "Guía",
      readTime: 8,
      date: "2026-06-10",
      featured: false,
      accent: "#0EA5E9",
      url: "articulos/que-es-chatgpt.html"
    },
    {
      id: "mejores-prompts-chatgpt",
      title: "Los 50 mejores prompts para ChatGPT en 2026",
      excerpt: "Prompts listos para copiar y pegar organizados por categoría: trabajo, escritura, código, marketing, estudio y creatividad. Optimizados para GPT-4o.",
      tag: "Guía práctica",
      readTime: 10,
      date: "2026-06-10",
      featured: false,
      accent: "#34A853",
      url: "articulos/mejores-prompts-chatgpt.html"
    },
    {
      id: "midjourney-vs-dalle-3",
      title: "Midjourney vs DALL-E 3: ¿cuál genera mejores imágenes en 2026?",
      excerpt: "Comparativa completa con benchmarks reales de calidad, precio, facilidad de uso y casos de uso. Veredicto claro para cada perfil.",
      tag: "Comparativa",
      readTime: 9,
      date: "2026-06-10",
      featured: false,
      accent: "#D4A754",
      url: "articulos/midjourney-vs-dalle-3.html"
    }
  ],

  glossary: [
    { term: "LLM",              def: "Large Language Model. Modelo de lenguaje de gran escala entrenado para predecir y generar texto mediante aprendizaje en enormes corpus de datos." },
    { term: "Token",            def: "Unidad mínima de texto que procesa un LLM. Equivale aproximadamente a ¾ de una palabra en inglés. Los precios de las APIs se expresan en coste por millón de tokens." },
    { term: "Prompt",           def: "Instrucción o texto de entrada que se le proporciona a un modelo para obtener una respuesta. Su diseño —prompt engineering— es clave para obtener resultados óptimos." },
    { term: "RAG",              def: "Retrieval-Augmented Generation. Técnica que permite a un LLM consultar una base de datos externa de documentos antes de responder, reduciendo alucinaciones y ampliando su conocimiento." },
    { term: "Fine-tuning",      def: "Proceso de entrenamiento adicional de un modelo preentrenado sobre un conjunto de datos específico, adaptándolo a un dominio o tarea concreta." },
    { term: "Temperatura",      def: "Parámetro que controla la aleatoriedad en las respuestas de un LLM. Valores altos (>1) generan texto más creativo e impredecible; valores bajos (<0.2) producen respuestas más deterministas." },
    { term: "Parámetros",       def: "Los pesos numéricos que definen el comportamiento de una red neuronal. Más parámetros implican mayor capacidad, aunque no necesariamente mejor rendimiento en tareas específicas." },
    { term: "Transformer",      def: "Arquitectura de red neuronal basada en mecanismos de atención, introducida por Google en 2017. Es la base de casi todos los LLMs modernos, incluyendo GPT, Claude y Gemini." },
    { term: "Embeddings",       def: "Representación vectorial densa de texto, imágenes u otros datos. Los embeddings capturan relaciones semánticas: palabras similares tienen vectores próximos en el espacio matemático." },
    { term: "Vector Database",  def: "Base de datos optimizada para almacenar y buscar embeddings. Fundamental en arquitecturas RAG. Ejemplos: Pinecone, Weaviate, Chroma, pgvector." },
    { term: "Chain of Thought", def: "Técnica de prompting en la que se pide al modelo que 'piense en voz alta' antes de dar la respuesta final. Mejora significativamente el rendimiento en tareas de razonamiento." },
    { term: "RLHF",             def: "Reinforcement Learning from Human Feedback. Método de entrenamiento donde humanos clasifican respuestas del modelo, y ese feedback se usa para mejorar su alineación." },
    { term: "Alucinación",      def: "Fenómeno en el que un LLM genera información falsa pero presentada con confianza. Causada por el mecanismo de predicción estadística del siguiente token." },
    { term: "Context Window",   def: "Cantidad máxima de texto (en tokens) que un modelo puede procesar en una sola interacción, incluyendo el historial de conversación. Varía entre 4K y 2M tokens según el modelo." },
    { term: "Multimodal",       def: "Capacidad de un modelo para procesar y generar varios tipos de datos: texto, imágenes, audio o vídeo. GPT-4o y Gemini son ejemplos destacados." },
    { term: "Agente de IA",     def: "Sistema autónomo que usa un LLM como núcleo de razonamiento y puede ejecutar acciones en el mundo real: buscar en internet, escribir código, llamar APIs o controlar ordenadores." },
    { term: "Benchmark",        def: "Conjunto estandarizado de pruebas para medir el rendimiento de un modelo. Los más usados: MMLU, HumanEval, MATH, HellaSwag, BIG-Bench." },
    { term: "Inferencia",       def: "El proceso de usar un modelo ya entrenado para generar respuestas. Contrasta con el entrenamiento. La velocidad de inferencia se mide en tokens por segundo." },
    { term: "Foundation Model", def: "Modelo base de gran escala preentrenado en datos masivos que sirve de punto de partida para adaptarse a tareas específicas mediante fine-tuning o prompting." },
    { term: "Preentrenamiento",  def: "Primera fase del desarrollo de un LLM: entrenamiento autosupervisado sobre billones de tokens de texto para que el modelo aprenda estadísticas del lenguaje." },
    { term: "Few-shot",         def: "Capacidad de un LLM para realizar una tarea con muy pocos ejemplos (entre 1 y 10) incluidos en el prompt, sin necesidad de reentrenamiento." },
    { term: "Zero-shot",        def: "Capacidad de un modelo para ejecutar tareas sin ningún ejemplo previo, solo con una descripción de la tarea en lenguaje natural." },
    { term: "MMLU",             def: "Massive Multitask Language Understanding. Benchmark de 57 áreas de conocimiento, desde matemáticas hasta derecho, usado para medir el conocimiento general de un LLM." },
    { term: "Tokenización",     def: "Proceso de dividir texto en tokens antes de pasarlo al modelo. Cada modelo usa su propio tokenizador (BPE, WordPiece, etc.) que afecta al coste y límites de contexto." },
    { term: "MoE",              def: "Mixture of Experts. Arquitectura donde solo se activa un subconjunto de parámetros por token, reduciendo el coste computacional manteniendo la capacidad de modelos más grandes." },
    { term: "Guardrails",       def: "Capas de seguridad implementadas sobre un LLM para prevenir outputs dañinos, sesgados o inapropiados. Pueden ser prompts de sistema, clasificadores o filtros post-generación." },
    { term: "Alineación",       def: "Campo de investigación que estudia cómo hacer que los sistemas de IA actúen conforme a los valores e intenciones humanas, especialmente a medida que aumenta su capacidad." },
    { term: "Cuantización",     def: "Técnica para reducir el tamaño de un modelo disminuyendo la precisión numérica de sus pesos (de float32 a int4, por ejemplo). Permite ejecutar modelos grandes en hardware convencional." },
    { term: "Distilación",      def: "Entrenamiento de un modelo pequeño (alumno) para imitar el comportamiento de uno grande (maestro). Produce modelos más eficientes con rendimiento cercano al original." },
    { term: "Latencia",         def: "Tiempo desde que se envía un prompt hasta recibir el primer token de respuesta. Métrica crítica en aplicaciones interactivas, distinta del throughput total." }
  ]
};
